default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password: kizrootkiz
    
development:
  <<: *default
  database: demo_development


test:
  <<: *default
  database: demo_test


 # On Heroku and other platform providers, you may have a full connection URL
 # available as an environment variable. For example:
 #
 #   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
 #
 # You can use this database configuration with:
 #
 #   production:
 #      url: <%= ENV['DATABASE_URL'] %>
 #

production:
  <<: *default
  database: demo_production
  username: root
  password: <%= ENV['MY_APP_DATABASE_PASSWORD'] %>



